services:
  app:
    image: mcr.microsoft.com/devcontainers/base:resolute
    command: sleep infinity
    volumes:
      - .:/workspace
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://sidemeetings@db/sidemeetings
    depends_on:
      - db
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  db:
    image: postgres:18
    volumes:
      - postgresdb-data:/var/lib/postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_DB=sidemeetings
      - POSTGRES_USER=sidemeetings
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@ietf.org
      - PGADMIN_DEFAULT_PASSWORD=dev
      - PGADMIN_CONFIG_LOGIN_BANNER="Login with dev@ietf.org / dev"
      - PGADMIN_DISABLE_POSTFIX=True
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - SCRIPT_NAME=/pgadmin
    depends_on:
      - db
    volumes:
      - ./docker/configs/pgadmin-servers.json:/pgadmin4/servers.json

volumes:
  postgresdb-data:
