name: Build and Release
run-name: Build ${{ github.run_number }} of branch ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to K8S'
        default: 'Skip'
        required: true
        type: choice
        options:
          - Skip
          - Staging Only
          - Staging + Prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # -----------------------------------------------------------------
  # BUILD
  # -----------------------------------------------------------------
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      pkg_version: ${{ steps.semver.outputs.nextStrict  }}

    steps:
      - uses: actions/checkout@v7

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          skipInvalidTags: true
          patchList: fix, bugfix, perf, refactor, test, tests, chore

      - name: Set package.json version
        run: |
          yq -iP '.version = "${{ steps.semver.outputs.nextStrict }}"' package.json -o json

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v7
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: .
          file: docker/release.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/ietf-tools/sidemeetings:${{ steps.semver.outputs.nextStrict }}

      - name: Create Draft Release
        uses: ncipollo/release-action@v1.21.0
        with:
          prerelease: true
          draft: false
          owner: ietf-tools
          repo: sidemeetings
          commit: ${{ github.sha }}
          tag: ${{ steps.semver.outputs.nextStrict }}
          name: ${{ steps.semver.outputs.nextStrict }}
          body: '*pending*'
          token: ${{ github.token }}

      - name: Generate CHANGELOG
        id: changelog
        uses: Requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ steps.semver.outputs.nextStrict }}
          toTag: ${{ steps.semver.outputs.current }}
          writeToFile: false

      - name: Finalize Release
        uses: ncipollo/release-action@v1.21.0
        with:
          allowUpdates: true
          makeLatest: true
          draft: false
          owner: ietf-tools
          repo: sidemeetings
          tag: ${{ steps.semver.outputs.nextStrict }}
          name: ${{ steps.semver.outputs.nextStrict }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

  # -----------------------------------------------------------------
  # STAGING
  # -----------------------------------------------------------------
  staging:
    name: Deploy to Staging
    if: ${{ !failure() && !cancelled() && (inputs.deploy == 'Staging Only' || inputs.deploy == 'Staging + Prod') }}
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: staging
    env:
      PKG_VERSION: ${{needs.build.outputs.pkg_version}}

    steps:
      - name: Deploy to staging
        uses: ietf-tools/workflow-dispatch-action@v1
        with:
          workflow: deploy.yml
          repo: ietf-tools/infra-k8s
          ref: main
          token: ${{ secrets.GH_INFRA_K8S_TOKEN }}
          inputs: '{ "environment":"${{ secrets.GHA_K8S_CLUSTER }}", "app":"sidemeetings", "appVersion":"${{ env.PKG_VERSION }}", "remoteRef":"${{ github.sha }}" }'

  # -----------------------------------------------------------------
  # PROD
  # -----------------------------------------------------------------
  prod:
    name: Deploy to Production
    if: ${{ !failure() && !cancelled() && (inputs.deploy == 'Staging + Prod') }}
    needs: [build, staging]
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      PKG_VERSION: ${{needs.build.outputs.pkg_version}}
    steps:
      - name: Deploy to production
        uses: ietf-tools/workflow-dispatch-action@v1
        with:
          workflow: deploy.yml
          repo: ietf-tools/infra-k8s
          ref: main
          token: ${{ secrets.GH_INFRA_K8S_TOKEN }}
          inputs: '{ "environment":"${{ secrets.GHA_K8S_CLUSTER }}", "app":"sidemeetings", "appVersion":"${{ env.PKG_VERSION }}", "remoteRef":"${{ github.sha }}" }'
